---

- name: shiny | install deb package
  tags:
    - package
  apt:
    deb: "{{ shiny_url }}"

- name: shiny | user
  tags:
    - user
  user:
    name: "{{ shiny_user }}"
    password: "{{ shiny_passwd | password_hash('sha512') }}"

- name: shiny | config
  tags:
    - config
  template:
    src: "{{ item }}.j2"
    dest: "/etc/shiny-server/{{ item }}"
  with_items:
    - shiny-server.conf
  notify: restart shiny

- name: shiny | nginx config
  include_role:
    name: nginx
    tasks_from: site.yml
  with_items: shiny

- name: shiny | logrotate config
  tags:
    - logrotate
  copy:
    dest: /etc/logrotate.d/shiny-server
    content: "{{ shiny_server_log }} {}"

- name: shiny | service
  tags:
    - service
  service:
    name: shiny-server
    state: started
    enabled: yes

